### PR TITLE
Maven wrapper and docker based builds

### PR DESCRIPTION
**Pull request by EugenMayer**
This PR adds the maven wrapper and docker based builds.

Docker based builds enable use to test linux-distro specific builds e.g. to test the different ca-certificate OS layouts, see #310

### CODE REVIEW

**Comment by Hakky54** [comment]
By the way, why do we need a maven wrapper? I think the docker is a nice addition, but i am not sure for the maven wrapper

**Comment by EugenMayer** [comment]
Because i would need to automate the mvn installation too otherwise. I really cannot see why maven folks still resist the wrapper paradigm :)

In gradle it is common practice since years with all the benefits included.

If you do not like it, you can remove it. But the maven installation automation is then on your TODO list :)

**Comment by Hakky54** [comment]
Yes, developers who use gradle mostly use de gradle wrapper. But I prefer to configure maven similar to java. Getting the binaries and configuring it to the shell path instead of bundling it together with a project. Mostly because I don't want to add additional files which are not mandatory... However I have one project where I have included it, see here: https://github.com/Hakky54/mutual-tls-ssl but that one is an exception 😄  as I wanted to provide a tutorial which anyone can easily run on their local machine while only requiring to install java.

Coming back to your PR. I have adjusted the test within the repo so it also validates the certificates when running on a linux machine. And I have also analysed your PR and I am assuming those docker images don't have maven so the wrapper is required to easily test it right?

You configured the new job to run a ubuntu container having QEMU which is able to run different docker images, in this case alphine and debian with jdk. But why did you specify git as docker image?

**Comment by Hakky54** [comment]
It seems like the build is failing because of the license plugin. You need to add the specific file which is causing the issue to the following exclusion list: https://github.com/Hakky54/sslcontext-kickstart/blob/0b645763631541b38011c73794502de1b241914f/pom.xml#L283

**Comment by Hakky54** [comment]
Hi @EugenMayer I resolved the license issue and merged your PR. However the build is failing. I temporally disabled the github action. Can you please have a look at it?

**Comment by EugenMayer** [comment]
@Hakky54 will do so next week, i'am busy traveling until end of the week and try to finish this on the weekend or start of the week

**Pull request merged**
