### PR TITLE
Add support for java modules

### PR DESCRIPTION
**Pull request by Hakky54**

### CODE REVIEW

**Comment by bjorndarri** [comment]
This is looking good, the only problem I see is

**requires jdk.httpserver;**

in the module-info.java.

It seems like this module is a test dependency, which means the actual module shouldn't require it.

You should remove this requires clause from the module-info.java files and add the module to the module path when compiling and running the tests, with the **\--add-modules** command line argument:

```shell
--add-modules jdk.httpserver
```

Note that you can do this via arguments in the maven compiler and test runner plugin configurations, as shown here:

[https://nipafx.dev/maven-on-java-9/](https://nipafx.dev/maven-on-java-9/)

I tried to do this myself but got bogged down in some Maven minutiae, as usual.

**Comment by Hakky54** [comment]
@bjorndarri I have managed to get it worked. What do you think of the result?
Sun HttpServer is replaced with Netty. The code will be initially compiled to Java 11 including the module-info.java. Afterwords it will be recompiled with Java 8. The resulting jar is compatible with Java 8 projects, however if someone is using Java 11+ with modules enabled it will automatically pick up the bundled module-info file from this library. You can give it a try if you want to test it on your side. Can you maybe have a look at the code, maybe review it? I must admit, it contains a-lot code changes...

**Comment by bjorndarri** [comment]
That's great, I'll take a look tomorrow.

**Comment by Hakky54** [comment]
> This just works!
>
> I tested both with a JDK8 based project as well as a JDK11 based one. All I had to do for JDK11 was replace the automatic-module-name in the requires clause with the new one, a voila, project built and ran just fine. And since I'm only using the core part of the library, no other code change were required.
>
> I skimmed the commits and didn't see anything out of order, well done 😎.

Awesome, thank you for taking your time to review it and trying it out locally and even providing a reference implementation from your side.

**Pull request merged**
