### PR TITLE
Added more descriptive usage of the SSLFactory

### PR DESCRIPTION
**Pull request by Hakky54**

### CODE REVIEW

**Comment by Hakky54** [comment]
@skarzhevskyy what do you think of the additional description regarding the different properties within the SSLFactory and the usage of them? I added it after you mentioned that it was not very clear when to use which property.

**Comment by skarzhevskyy** [comment]
@Hakky54   it sound like a book now. But I believe most people will just go by examples in "Tested HTTP Clients"
Questions will remains that if library API provides multiple options for example like sslSocketFactory and sslContext at the same time what needs to be set?   What will override what ...
I think this depends on library and is better be documented as comments in example for each library.

**Comment by skarzhevskyy** [comment]
@Hakky54   I should explain my use case of the library 
- when app is deployed ops just change the global java keystore with corporate keystore at best using -D for app startup.
- at some cases ops just update the JVM keystore. and would be afraid to changes  JVM version later one 
- once system needs to connect to multiple services each providing its keystore it becomes even more interesting since different ops teams will just want override global keystore and require instructions for this....

So I'm using sslcontext-kickstart to allow for option to configure SSL per services/endpoints  


As notes SSLFactory.builder().withProtocols  and withCiphers  would benefit with comments 
```
 You used to do this using -Djdk.tls.client.protocols   and -Dhttps.protocols 
```

**Comment by Hakky54** [comment]
>@Hakky54 it sound like a book now. But I believe most people will just go by examples in "Tested HTTP Clients"
Questions will remains that if library API provides multiple options for example like sslSocketFactory and sslContext at the same time what needs to be set? What will override what ...
I think this depends on library and is better be documented as comments in example for each library.

Yes indeed, the description looks more like a book or a blog. I think everyone can just use the list of tested client as a cheatsheet and that should be sufficient. If anyone has questions they can drop it into the github discussion or gitter as that is the correct place to discuss these kind of questions. 

>As notes SSLFactory.builder().withProtocols and withCiphers would benefit with comments
You used to do this using -Djdk.tls.client.protocols   and -Dhttps.protocols 

Good suggestion, I will add this.

>@Hakky54 I should explain my use case of the library
>- when app is deployed ops just change the global java keystore with corporate keystore at best using -D for app startup.
>- at some cases ops just update the JVM keystore. and would be afraid to changes JVM version later one
>- once system needs to connect to multiple services each providing its keystore it becomes even more interesting since different ops teams will just want override global keystore and require instructions for this....
>
>So I'm using sslcontext-kickstart to allow for option to configure SSL per services/endpoints

Really cool to hear how you guys are using it in your company! For me it is always a black box of how developers are using it on their projects.

**Pull request closed without merging**
