### PR TITLE
Added capability to conceal trusted certificates

### PR DESCRIPTION
**Pull request by Hakky54**

### CODE REVIEW

**Comment by Hakky54** [comment]
@gerardnorton I have made a WIP initial implementation. Can you maybe have a look at it?
What do you think, would this work for your situation? If you want to give it a try locally with your own application you can checkout this branch and build the snapshot locally to try it out. If something is missing we can still add it.

**Comment by gerardnorton** [comment]
Hi.
I have tested version 8.1.8-SNAPSHOT locally and it works perfectly.

:-)

**Comment by Hakky54** [comment]
Awesome, great to hear! I added it also to the documentation, see here: https://github.com/Hakky54/sslcontext-kickstart#hide-trusted-certificate-names-of-a-server

I will release a new version coming week, I will keep you up-to-date.

By the way, I did some testing with a huge collection of trusted certficates within a server and this is the results when the I don't configure the server with the new option:

Screenshot 2023-10-13 at 20 20 51

Amazing to see so much information is presented by the server itself.

**Comment by gerardnorton** [comment]
Yes.
But keep in mind that when you disable this, you are also disabling OCSP. This functionality is designed to prevent MITM attacks at the certificate level or for the validation of certificates on the client browser side.
It is only advisable to disable this in some cases, such as when you want to protect the identity of users accessing the APP with MTLS.

[https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol)

OCSP

:-)

**Comment by Hakky54** [comment]
Awesome, thank you for this additional context. By the way if you think the overal documentation can be improved, feel free to submit a PR. It seems like you have in-depth knowledge for these kind of topics.

**Comment by Hakky54** [comment]
@gerardnorton This option is now available in version `8.2.0`

**Pull request merged**
